Feature/objects table improvements
EyeSeeTea/d2-ui-components pull request #57
Opened 2019-07-26 11:38 UTC by tokland

Closes #10 

High Priority
- [x] ObjectsTable: Hide checkboxes if there are no fields with multiple set to true.
- [x] Apply branch fix/calculate-page-value
- [x] ObjectsTable: We have `initialSorting` as a required prop, make it optional and assume first sortable column ASC is the default order.
- [x] Update readme for ObjectsTable with explanation regarding prop 'key' to update it.

Low Priority
- [x] Reduce marginTop by 10px, too much space.
- [x] Change model prop to optional (See https://github.com/EyeSeeTea/metadata-synchronization/issues/7 -> Remove model prop from instance-configurator)
- [x] Hide details panel if table refreshes otherwise it can be confusing for the user.

2019-07-29 08:54 UTC, SferaDev commented
Found a "bug" with SyncRulesWizard in metadata-synchronization related to "Hide checkboxes if there are no fields with multiple set to true".

In the wizard we are using the multiple selection but without using the ObjectsTable's actions, instead we use the Wizard pagination. Now the checkboxes are gone and that functionality is gone.

We could either add a multiple selection action and it would continue working but I guess that's not the perfect solution.

![image](https://user-images.githubusercontent.com/2181866/62034991-42f28180-b1ef-11e9-9e43-b09ab6ab02a9.png)

2019-07-29 08:58 UTC, SferaDev requested changes
The only thing that blocks this PR is finding a wait for metadata-synchronization to force checkboxes without having a multi selection action

2019-07-29 08:58 UTC, SferaDev commented on src/objects-table/ObjectsTable.js
> +            sorting: this.props.initialSorting || this.getDefaultSorting(),
Tested. Works perfect!

2019-07-29 08:58 UTC, SferaDev commented on src/objects-table/ObjectsTable.js
> +    const pageCount = Math.ceil(total / pageSize);
Tested. Works perfect!

2019-07-29 08:58 UTC, SferaDev commented on src/objects-table/ObjectsTable.js
> +            <div style={styles.mainWrapper}>
Tested. Works perfect!

2019-07-29 12:06 UTC, tokland commented on src/objects-table/ObjectsTable.js
> +            sorting: this.props.initialSorting || this.getDefaultSorting(),
Fixed: eb7c55dc

2019-07-29 12:08 UTC, tokland commented
Selection column problem fixed in eb7c55dc. 

PR for metadata-sync: https://github.com/EyeSeeTea/metadata-synchronization/pull/139

2019-08-05 09:51 UTC, SferaDev approved these changes

2019-08-26 08:07 UTC, merged